package storageclassmap

import (
	"fmt"
)

var azureStorageClassMap = map[string]string{
	"Hot":                         "standard",
	"Standard":                    "standard",
	"Premium":                     "standard",
	"Premium LRS":                 "standard",
	"Premium ZRS":                 "standard",
	"Blob":                        "standard",
	"Block Blob":                  "standard",
	"Page Blob":                   "standard",
	"Append Blob":                 "standard",
	"Premium Block Blob":          "standard",
	"Premium Page Blob":           "standard",
	"Standard Page Blob":          "standard",
	"Standard Block Blob":         "standard",
	"Standard Append Blob":        "standard",
	"Files":                       "standard",
	"Premium Files":               "standard",
	"Disks":                       "standard",
	"Managed Disks":               "standard",
	"Ultra Disks":                 "standard",
	"SSD":                         "standard",
	"SSD LRS":                     "standard",
	"SSD ZRS":                     "standard",
	"Standard SSD":                "standard",
	"Standard SSD LRS":            "standard",
	"Standard SSD ZRS":            "standard",
	"Premium SSD":                 "standard",
	"Premium SSD LRS":             "standard",
	"Premium SSD ZRS":             "standard",
	"Premium SSD v2":              "standard",
	"Premium SSD v2 LRS":          "standard",
	"Premium SSD v2 ZRS":          "standard",
	"Ultra SSD":                   "standard",
	"Ultra SSD LRS":               "standard",
	"HDD":                         "standard",
	"Standard HDD":                "standard",
	"Standard HDD LRS":            "standard",
	"Standard LRS":                "standard",
	"Standard ZRS":                "standard",
	"Standard GRS":                "standard",
	"Standard GZRS":               "standard",
	"Standard RAGRS":              "standard",
	"Standard RAGZRS":             "standard",
	"GZRS":                        "standard",
	"GRS":                         "standard",
	"LRS":                         "standard",
	"ZRS":                         "standard",
	"RA-GRS":                      "standard",
	"RA-GZRS":                     "standard",
	"Account Encrypted":           "standard",
	"Account Encrypted LRS":       "standard",
	"Account Encrypted ZRS":       "standard",
	"Account Encrypted GRS":       "standard",
	"Account Encrypted GZRS":      "standard",
	"Account Encrypted RA-GRS":    "standard",
	"Account Encrypted RA-GZRS":   "standard",
	"Hot LRS":                     "standard",
	"Hot ZRS":                     "standard",
	"Hot GRS":                     "standard",
	"Hot GZRS":                    "standard",
	"Cool":                        "infrequent_access",
	"Cool LRS":                    "infrequent_access",
	"Cool ZRS":                    "infrequent_access",
	"Cool GRS":                    "infrequent_access",
	"Cool GZRS":                   "infrequent_access",
	"Cold":                        "infrequent_access",
	"Cold LRS":                    "infrequent_access",
	"Cold ZRS":                    "infrequent_access",
	"Cold GRS":                    "infrequent_access",
	"Cold GZRS":                   "infrequent_access",
	"Archive":                     "archive",
	"Archive LRS":                 "archive",
	"Archive ZRS":                 "archive",
	"Archive GRS":                 "archive",
	"Archive GZRS":                "archive",
}

// MapAzureStorageClass resolves an Azure storage class to a canonical class.
func MapAzureStorageClass(rawClass string) (string, error) {
	canonical, ok := azureStorageClassMap[rawClass]
	if !ok {
		return "", fmt.Errorf("%w: %q", ErrUnmappedStorageClass, rawClass)
	}
	return canonical, nil
}
