/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/login": {
    /** Validates credentials with timing-safe comparison and issues JWT access token and opaque refresh token pair */
    post: {
      parameters: {
        body: {
          /** Login credentials */
          request: definitions["rest.LoginRequest"];
        };
      };
      responses: {
        /** Authentication successful */
        200: {
          schema: definitions["rest.LoginResponse"];
        };
        /** Malformed JSON request */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Invalid email or password */
        401: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Method Not Allowed */
        405: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Rate limit exceeded */
        429: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/auth/logout": {
    /** Revokes the specified refresh token and purges it from the rotation cache */
    post: {
      parameters: {
        body: {
          /** Logout parameters */
          request: definitions["rest.LogoutRequest"];
        };
      };
      responses: {
        /** Session revoked successfully */
        200: {
          schema: definitions["rest.LogoutResponse"];
        };
        /** Invalid or missing refresh_token */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Method Not Allowed */
        405: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/auth/refresh": {
    /** Rotates a valid refresh token, minting a new access and refresh token pair with idempotency-key gated replay and whole-family theft containment */
    post: {
      parameters: {
        body: {
          /** Refresh token parameters */
          request: definitions["rest.RefreshRequest"];
        };
      };
      responses: {
        /** Tokens rotated successfully */
        200: {
          schema: definitions["rest.RefreshResponse"];
        };
        /** Invalid or missing refresh_token or idempotency_key */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Invalid, expired, revoked, or compromised token family */
        401: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Method Not Allowed */
        405: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/auth/resend-verification": {
    /** Requests a fresh email verification link without revealing account existence */
    post: {
      parameters: {
        body: {
          /** Recipient email */
          request: definitions["rest.ResendVerificationRequest"];
        };
      };
      responses: {
        /** Verification email request accepted */
        202: {
          schema: definitions["rest.ResendVerificationResponse"];
        };
        /** Malformed request or missing email */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Method Not Allowed */
        405: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Too many verification requests */
        429: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/auth/signup": {
    /** Creates a new user account with email and password */
    post: {
      parameters: {
        body: {
          /** Signup parameters */
          request: definitions["rest.SignupRequest"];
        };
      };
      responses: {
        /** User registered successfully */
        201: {
          schema: definitions["rest.SignupResponse"];
        };
        /** Invalid email or password format */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Method Not Allowed */
        405: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** User with this email already exists */
        409: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/auth/verify-email": {
    /** Consumes a single-use verification token to activate a user account */
    post: {
      parameters: {
        body: {
          /** Verification token */
          request: definitions["rest.VerifyEmailRequest"];
        };
      };
      responses: {
        /** Email verified successfully */
        200: {
          schema: definitions["rest.VerifyEmailResponse"];
        };
        /** Malformed request or missing token */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Verification token not found */
        404: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Method Not Allowed */
        405: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Verification token already consumed */
        409: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Verification token expired */
        410: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Rate limit exceeded */
        429: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/calculate": {
    /** Calculates composite pricing across cloud providers for requested compute, storage, network, database, NoSQL, Kubernetes, and serverless specs. */
    post: {
      parameters: {
        body: {
          /** Composite workload request payload */
          payload: definitions["rest.CalculateRequestBody"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rest.CalculateResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Too Many Requests */
        429: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/catalog/compute/instances": {
    /** Returns paginated virtual machine specifications filtered by provider, category, family, and vCPU/RAM ranges. */
    get: {
      parameters: {
        query: {
          /** Cloud provider (aws, azure, gcp, etc.) */
          provider?: string;
          /** Instance category (general_purpose, compute_optimized, etc.) */
          category?: string;
          /** Instance family (t3, c5, Standard_D, etc.) */
          instance_family?: string;
          /** Minimum vCPU count */
          min_vcpu?: number;
          /** Maximum vCPU count */
          max_vcpu?: number;
          /** Minimum RAM in GiB */
          min_memory_gib?: number;
          /** Maximum RAM in GiB */
          max_memory_gib?: number;
          /** Limit (default: 50, max: 200) */
          limit?: number;
          /** Offset (default: 0) */
          offset?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rest.CatalogInstancesResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/catalog/compute/summary": {
    /** Returns total instances, provider counts, and category breakdowns across all cloud providers. */
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["rest.CatalogSummaryResponse"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/prices/compute": {
    /** Returns normalized compute pricing across cloud providers for requested specs. */
    get: {
      parameters: {
        query: {
          /** Requested vCPU count (e.g. 4) */
          vcpu?: number;
          /** Requested RAM in GB (e.g. 16) */
          ram_gb?: number;
          /** Instance family filter (e.g. t3, c5) */
          family?: string;
          /** Canonical region group (default: us-east) */
          region?: string;
          /** Target currency code (default: USD) */
          currency?: string;
          /** Strict instance family matching (default: true) */
          strict_family?: boolean;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rest.ComputeComparisonResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Too Many Requests */
        429: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/prices/database": {
    /** Returns normalized relational database pricing across cloud providers (AWS, Azure, GCP) for requested specs. */
    get: {
      parameters: {
        query: {
          /** Requested database engine (e.g. postgresql, mysql, sqlserver) */
          engine?: string;
          /** Requested vCPU count (e.g. 4) */
          vcpu?: number;
          /** Requested RAM in GB (e.g. 16) */
          ram_gb?: number;
          /** Requested storage in GB (e.g. 100) */
          storage_gb?: number;
          /** Requested provisioned IOPS (e.g. 3000) */
          iops?: number;
          /** High Availability / Multi-AZ deployment (default: false) */
          multi_az?: boolean;
          /** Storage family preference (e.g. gp3, ssd, io1) */
          storage_family?: string;
          /** Canonical region group (default: us-east) */
          region?: string;
          /** Target currency code (default: USD) */
          currency?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rest.DatabaseComparisonResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Too Many Requests */
        429: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/prices/database-nosql": {
    /** Returns normalized NoSQL database pricing across cloud providers (AWS DynamoDB, Azure Cosmos DB, GCP Firestore) for requested specs. */
    get: {
      parameters: {
        query: {
          /** Requested NoSQL data model (e.g. document, key_value, wide_column, graph) */
          data_model?: string;
          /** Requested pricing mode (provisioned, on_demand, serverless; default: provisioned) */
          pricing_mode?: string;
          /** Requested reads per second (e.g. 100) */
          read_units?: number;
          /** Requested writes per second (e.g. 20) */
          write_units?: number;
          /** Requested storage in GB (e.g. 50) */
          storage_gb?: number;
          /** Storage class preference (e.g. standard, infrequent_access, analytical) */
          storage_class?: string;
          /** High Availability / Multi-Region replication (default: false) */
          multi_region?: boolean;
          /** Canonical region group (default: us-east) */
          region?: string;
          /** Target currency code (default: USD) */
          currency?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rest.DatabaseNoSQLComparisonResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Too Many Requests */
        429: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/prices/kubernetes": {
    /** Returns normalized Kubernetes control-plane pricing across cloud providers (AWS EKS, Azure AKS, GCP GKE) for requested tier. */
    get: {
      parameters: {
        query: {
          /** Requested Kubernetes cluster tier (free, standard, extended_support; default: standard) */
          tier?: string;
          /** GCP-specific cluster topology for credit application (zonal, regional, autopilot; default: zonal) */
          cluster_topology?: string;
          /** Canonical region group (default: us-east) */
          region?: string;
          /** Target currency code (default: USD) */
          currency?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rest.KubernetesComparisonResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Too Many Requests */
        429: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/prices/network": {
    /** Returns normalized network / data transfer egress pricing across cloud providers (AWS, Azure, GCP) for requested specs. */
    get: {
      parameters: {
        query: {
          /** Requested network egress in GB (e.g. 500, max 10000000) */
          egress_gb?: string;
          /** Canonical transfer type (intra_region, inter_region, internet_egress) */
          transfer_type?: string;
          /** Canonical region group (default: us-east) */
          region?: string;
          /** Target currency code (default: USD) */
          currency?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rest.NetworkComparisonResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Too Many Requests */
        429: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/prices/serverless": {
    /** Returns normalized Serverless compute (FaaS) pricing across cloud providers (AWS Lambda, Azure Functions, GCP Cloud Functions) for requested workload. */
    get: {
      parameters: {
        query: {
          /** Requested CPU architecture (x86_64, arm64; default: x86_64) */
          architecture?: string;
          /** Requested serverless tier (consumption, flex_consumption, 1st_gen, 2nd_gen; default: consumption) */
          tier?: string;
          /** Monthly invocation requests (default: 1000000) */
          requests_per_month?: number;
          /** Function allocated memory in MB (128 - 10240, default: 512) */
          memory_mb?: number;
          /** Average execution duration in ms (1 - 900000, default: 200) */
          execution_duration_ms?: number;
          /** Canonical region group (default: us-east) */
          region?: string;
          /** Target currency code (default: USD) */
          currency?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rest.ServerlessComparisonResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Too Many Requests */
        429: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/prices/storage": {
    /** Returns normalized storage pricing across cloud providers (AWS, Azure, GCP) for requested specs. */
    get: {
      parameters: {
        query: {
          /** Requested storage size in GB (e.g. 500, max 1000000) */
          size_gb?: string;
          /** Requested canonical storage class (e.g. standard, infrequent_access, archive) */
          storage_class?: string;
          /** Canonical region group (default: us-east) */
          region?: string;
          /** Target currency code (default: USD) */
          currency?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["rest.StorageComparisonResponse"];
        };
        /** Bad Request */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Too Many Requests */
        429: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
  "/api/v1/providers/{provider}/status": {
    /** Returns the latest successful fetch timestamp, per-category observation count, staleness flag, and active DLQ failure records for the specified cloud provider. */
    get: {
      parameters: {
        path: {
          /** Cloud provider identifier (e.g. aws, azure, gcp, oracle, ibm, alibaba, digitalocean) */
          provider: string;
        };
      };
      responses: {
        /** Provider status and category freshness details */
        200: {
          schema: definitions["rest.ProviderStatusResponse"];
        };
        /** Invalid Parameters */
        400: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Provider Not Found */
        404: {
          schema: definitions["middleware.RFC7807Error"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["middleware.RFC7807Error"];
        };
      };
    };
  };
}

export interface definitions {
  "domain.ComputeAttributes": {
    family?: string;
    ram_gb?: number;
    vcpu?: number;
  };
  "domain.ComputeCatalogItem": {
    attributes?: definitions["domain.ComputeAttributes"];
    category?: string;
    cpu_architecture?: string;
    display_name?: string;
    first_seen_at?: string;
    gpu_count?: number;
    gpu_type?: string;
    id?: number;
    instance_family?: string;
    instance_type_id?: string;
    is_burstable?: boolean;
    is_current_gen?: boolean;
    last_seen_at?: string;
    memory_gib?: number;
    provider?: string;
    vcpu?: number;
  };
  "domain.DatabaseNoSQLAttributes": {
    /** @description "throughput", "storage", "request_operations" */
    component_type?: string;
    /** @description "document", "key_value", "wide_column", "graph", "multi_model" */
    data_model?: string;
    /** @description Multi-region replication / global distribution */
    multi_region?: boolean;
    /** @description "provisioned", "on_demand", "serverless" */
    pricing_mode?: string;
    /** @description Provisioned reads/sec (RCU/RU/s) or request rate */
    read_units?: number;
    /** @description Number of replica regions (default: 1) */
    replication_zones?: number;
    /** @description "standard", "infrequent_access", "analytical" */
    storage_class?: string;
    /** @description Storage capacity in GiB */
    storage_gb?: number;
    /** @description Provisioned writes/sec (WCU/RU/s) or request rate */
    write_units?: number;
  };
  "domain.DatabaseRDBMSAttributes": {
    /** @description "instance" or "storage" */
    component_type?: string;
    /** @description "standard", "flexible", "burstable", "aurora" */
    deployment_tier?: string;
    /** @description "postgresql", "mysql", "sqlserver", "mariadb", "oracle" */
    engine?: string;
    /** @description Provisioned IOPS */
    iops?: number;
    /** @description High Availability deployment */
    multi_az?: boolean;
    /** @description Memory capacity in GiB (0 for pure storage rows) */
    ram_gb?: number;
    /** @description "gp3", "gp2", "io1", "ssd", "hdd" */
    storage_family?: string;
    /** @description Storage capacity in GiB (0 for pure instance rows) */
    storage_gb?: number;
    /** @description Number of vCPUs (0 for pure storage rows) */
    vcpu?: number;
  };
  "domain.KubernetesAttributes": {
    /** @description "zonal", "regional", "autopilot" — GCP-specific */
    cluster_topology?: string;
    /** @description "free", "standard", "extended_support" */
    tier?: string;
  };
  "domain.NetworkAttributes": {
    egress_gb?: number;
    transfer_type?: string;
  };
  "domain.ServerlessRateAttributes": {
    /** @description "x86_64", "arm64" */
    architecture?: string;
    /** @description "request_fee", "duration_fee", "duration_fee_cpu", "duration_fee_memory" */
    component_type?: string;
    /** @description "consumption", "flex_consumption", "1st_gen", "2nd_gen" */
    tier?: string;
    /** @description "per_million_requests", "per_request", "per_10_requests", "per_gb_second", etc. */
    unit?: string;
  };
  "domain.StorageAttributes": {
    /**
     * @description IOPS holds provisioned IOPS where reported (e.g. block storage EBS gp3/io2).
     * Currently unpopulated for S3/Blob/GCS object storage in stage 1.4.
     */
    iops?: number;
    size_gb?: number;
    storage_class?: string;
  };
  "middleware.RFC7807Error": {
    detail?: string;
    instance?: string;
    status?: number;
    title?: string;
    type?: string;
  };
  "rest.CalculateCategoryResult": {
    match_delta_pct?: number;
    match_quality?: string;
    missing_attributes?: string[];
    normalized_hourly_usd?: number;
    sku_id?: string;
    stale?: boolean;
  };
  "rest.CalculateMeta": {
    api_version?: string;
    generated_at?: string;
    request?: definitions["rest.CalculateRequestBody"];
  };
  "rest.CalculateProviderResult": {
    categories?: { [key: string]: definitions["rest.CalculateCategoryResult"] };
    partial?: boolean;
    partial_total_normalized_hourly_usd?: number;
    provider?: string;
    total_normalized_hourly_usd?: number;
  };
  "rest.CalculateRequestBody": {
    compute?: definitions["domain.ComputeAttributes"];
    currency?: string;
    /** @description alias for database_rdbms */
    database?: definitions["domain.DatabaseRDBMSAttributes"];
    database_nosql?: definitions["domain.DatabaseNoSQLAttributes"];
    database_rdbms?: definitions["domain.DatabaseRDBMSAttributes"];
    kubernetes?: definitions["domain.KubernetesAttributes"];
    network?: definitions["domain.NetworkAttributes"];
    region?: string;
    serverless?: definitions["rest.ServerlessWorkloadPayload"];
    storage?: definitions["domain.StorageAttributes"];
    strict_family?: boolean;
  };
  "rest.CalculateResponse": {
    meta?: definitions["rest.CalculateMeta"];
    results?: definitions["rest.CalculateProviderResult"][];
    warnings?: definitions["rest.ProviderWarning"][];
  };
  "rest.CatalogInstancesResponse": {
    count?: number;
    instances?: definitions["domain.ComputeCatalogItem"][];
    total?: number;
  };
  "rest.CatalogSummaryResponse": {
    category_breakdown?: { [key: string]: { [key: string]: number } };
    provider_totals?: { [key: string]: number };
    total_instances?: number;
  };
  "rest.CategoryStatusResponse": {
    /** @example compute */
    category?: string;
    dlq?: definitions["rest.DLQStatusResponse"];
    last_fetched_at?: string;
    last_seen_at?: string;
    /** @example 450 */
    observation_count?: number;
    /** @example false */
    stale?: boolean;
    /** @example 168 */
    staleness_threshold_hours?: number;
    /** @example true */
    supported?: boolean;
  };
  "rest.ComputeComparisonMeta": {
    api_version?: string;
    generated_at?: string;
    query?: { [key: string]: unknown };
  };
  "rest.ComputeComparisonResponse": {
    meta?: definitions["rest.ComputeComparisonMeta"];
    results?: definitions["rest.ComputeResultEntry"][];
    warnings?: definitions["rest.ProviderWarning"][];
  };
  "rest.ComputeResultEntry": {
    fetched_at?: string;
    match_delta_pct?: number;
    match_quality?: string;
    matched_spec?: definitions["domain.ComputeAttributes"];
    missing_attributes?: string[];
    normalized_hourly_usd?: number;
    price?: definitions["rest.PriceDetail"];
    provider?: string;
    sku_id?: string;
    stale?: boolean;
  };
  "rest.DLQStatusResponse": {
    /** @example 3 */
    consecutive_failures?: number;
    /** @example 503 Service Unavailable */
    last_error?: string;
    /** @example failed */
    status?: string;
    timestamp?: string;
  };
  "rest.DatabaseComparisonMeta": {
    api_version?: string;
    generated_at?: string;
    query?: { [key: string]: unknown };
  };
  "rest.DatabaseComparisonResponse": {
    meta?: definitions["rest.DatabaseComparisonMeta"];
    results?: definitions["rest.DatabaseResultEntry"][];
    warnings?: definitions["rest.ProviderWarning"][];
  };
  "rest.DatabaseNoSQLComparisonMeta": {
    api_version?: string;
    generated_at?: string;
    query?: { [key: string]: unknown };
  };
  "rest.DatabaseNoSQLComparisonResponse": {
    meta?: definitions["rest.DatabaseNoSQLComparisonMeta"];
    results?: definitions["rest.DatabaseNoSQLResultEntry"][];
    warnings?: definitions["rest.ProviderWarning"][];
  };
  "rest.DatabaseNoSQLResultEntry": {
    fetched_at?: string;
    match_delta_pct?: number;
    match_quality?: string;
    matched_spec?: definitions["domain.DatabaseNoSQLAttributes"];
    missing_attributes?: string[];
    normalized_hourly_usd?: number;
    price?: definitions["rest.PriceDetail"];
    provider?: string;
    sku_id?: string;
    stale?: boolean;
  };
  "rest.DatabaseResultEntry": {
    fetched_at?: string;
    match_delta_pct?: number;
    match_quality?: string;
    matched_spec?: definitions["domain.DatabaseRDBMSAttributes"];
    missing_attributes?: string[];
    normalized_hourly_usd?: number;
    price?: definitions["rest.PriceDetail"];
    provider?: string;
    sku_id?: string;
    stale?: boolean;
  };
  "rest.KubernetesComparisonMeta": {
    api_version?: string;
    generated_at?: string;
    query?: { [key: string]: unknown };
  };
  "rest.KubernetesComparisonResponse": {
    meta?: definitions["rest.KubernetesComparisonMeta"];
    results?: definitions["rest.KubernetesResultEntry"][];
    warnings?: definitions["rest.ProviderWarning"][];
  };
  "rest.KubernetesResultEntry": {
    fetched_at?: string;
    match_delta_pct?: number;
    match_quality?: string;
    matched_spec?: definitions["domain.KubernetesAttributes"];
    missing_attributes?: string[];
    normalized_hourly_usd?: number;
    price?: definitions["rest.PriceDetail"];
    provider?: string;
    sku_id?: string;
    stale?: boolean;
  };
  "rest.LoginRequest": {
    email?: string;
    password?: string;
  };
  "rest.LoginResponse": {
    access_token?: string;
    expires_in?: number;
    refresh_token?: string;
    token_type?: string;
  };
  "rest.LogoutRequest": {
    refresh_token?: string;
  };
  "rest.LogoutResponse": {
    message?: string;
  };
  "rest.NetworkComparisonMeta": {
    api_version?: string;
    generated_at?: string;
    query?: { [key: string]: unknown };
  };
  "rest.NetworkComparisonResponse": {
    meta?: definitions["rest.NetworkComparisonMeta"];
    results?: definitions["rest.NetworkResultEntry"][];
    warnings?: definitions["rest.ProviderWarning"][];
  };
  "rest.NetworkResultEntry": {
    fetched_at?: string;
    match_delta_pct?: number;
    match_quality?: string;
    matched_spec?: definitions["domain.NetworkAttributes"];
    missing_attributes?: string[];
    monthly_cost_usd?: number;
    normalized_hourly_usd?: number;
    price?: definitions["rest.PriceDetail"];
    provider?: string;
    sku_id?: string;
    stale?: boolean;
  };
  "rest.PriceDetail": {
    amount?: number;
    currency?: string;
    unit?: string;
  };
  "rest.ProviderStatusResponse": {
    categories?: { [key: string]: definitions["rest.CategoryStatusResponse"] };
    last_successful_fetch?: string;
    /** @example aws */
    provider?: string;
    /** @example false */
    stale?: boolean;
    /** @example healthy */
    status?: string;
    warnings?: definitions["rest.ProviderStatusWarningResponse"][];
  };
  "rest.ProviderStatusWarningResponse": {
    /** @example not_yet_ingested */
    code?: string;
    /** @example Oracle OCI ingestion currently unavailable */
    message?: string;
    /** @example oracle */
    provider?: string;
  };
  "rest.ProviderWarning": {
    code?: string;
    message?: string;
    provider?: string;
  };
  "rest.RefreshRequest": {
    idempotency_key?: string;
    refresh_token?: string;
  };
  "rest.RefreshResponse": {
    access_token?: string;
    expires_in?: number;
    refresh_token?: string;
    token_type?: string;
  };
  "rest.ResendVerificationRequest": {
    email?: string;
  };
  "rest.ResendVerificationResponse": {
    message?: string;
  };
  "rest.ServerlessComparisonMeta": {
    api_version?: string;
    generated_at?: string;
    query?: { [key: string]: unknown };
  };
  "rest.ServerlessComparisonResponse": {
    meta?: definitions["rest.ServerlessComparisonMeta"];
    results?: definitions["rest.ServerlessResultEntry"][];
    warnings?: definitions["rest.ProviderWarning"][];
  };
  "rest.ServerlessResultEntry": {
    fetched_at?: string;
    match_delta_pct?: number;
    match_quality?: string;
    matched_spec?: definitions["domain.ServerlessRateAttributes"];
    missing_attributes?: string[];
    normalized_hourly_usd?: number;
    normalized_monthly_usd?: number;
    price?: definitions["rest.PriceDetail"];
    provider?: string;
    sku_id?: string;
    stale?: boolean;
  };
  "rest.ServerlessWorkloadPayload": {
    architecture?: string;
    execution_duration_ms?: number;
    memory_mb?: number;
    requests_per_month?: number;
    tier?: string;
  };
  "rest.SignupRequest": {
    email?: string;
    password?: string;
  };
  "rest.SignupResponse": {
    created_at?: string;
    email?: string;
    id?: string;
  };
  "rest.StorageComparisonMeta": {
    api_version?: string;
    generated_at?: string;
    query?: { [key: string]: unknown };
  };
  "rest.StorageComparisonResponse": {
    meta?: definitions["rest.StorageComparisonMeta"];
    results?: definitions["rest.StorageResultEntry"][];
    warnings?: definitions["rest.ProviderWarning"][];
  };
  "rest.StorageResultEntry": {
    fetched_at?: string;
    match_delta_pct?: number;
    match_quality?: string;
    matched_spec?: definitions["domain.StorageAttributes"];
    missing_attributes?: string[];
    monthly_cost_usd?: number;
    normalized_hourly_usd?: number;
    price?: definitions["rest.PriceDetail"];
    provider?: string;
    sku_id?: string;
    stale?: boolean;
  };
  "rest.VerifyEmailRequest": {
    token?: string;
  };
  "rest.VerifyEmailResponse": {
    message?: string;
  };
}

export interface operations {}

export interface external {}
