[database]
host = {{ env "CLOUDVITTA_DATABASE_MIGRATION_HOST" }}
port = {{ env "CLOUDVITTA_DATABASE_PORT" }}
database = {{ env "CLOUDVITTA_DATABASE_NAME" }}
user = {{ env "CLOUDVITTA_DATABASE_USER" }}
password = {{ env "CLOUDVITTA_DATABASE_PASSWORD" }}

[data]
