// Package openapi GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/calculate": {
            "post": {
                "description": "Calculates server-side composite normalized hourly pricing across cloud providers (AWS, Azure, GCP) for multi-category workloads (compute, storage, network).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prices"
                ],
                "summary": "Calculate composite workload pricing",
                "parameters": [
                    {
                        "description": "Workload calculation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.CalculateRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.CalculateComparisonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.RFC7807Error"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "$ref": "#/definitions/middleware.RFC7807Error"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/middleware.RFC7807Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.RFC7807Error"
                        }
                    }
                }
            }
        },
        "/api/v1/prices/compute": {
            "get": {
                "description": "Returns normalized compute pricing across cloud providers for requested specs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prices"
                ],
                "summary": "Get compute pricing comparison",
                "parameters": [
                    {
                        "type": "number",
                        "description": "Requested vCPU count (e.g. 4)",
                        "name": "vcpu",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Requested RAM in GB (e.g. 16)",
                        "name": "ram_gb",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Instance family filter (e.g. t3, c5)",
                        "name": "family",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Canonical region group (default: us-east)",
                        "name": "region",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Target currency code (default: USD)",
                        "name": "currency",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Strict instance family matching (default: true)",
                        "name": "strict_family",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.ComputeComparisonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.RFC7807Error"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/middleware.RFC7807Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.RFC7807Error"
                        }
                    }
                }
            }
        },
        "/api/v1/prices/network": {
            "get": {
                "description": "Returns normalized network / data transfer egress pricing across cloud providers (AWS, Azure, GCP) for requested specs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prices"
                ],
                "summary": "Get network pricing comparison",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Requested network egress in GB (e.g. 500, max 10000000)",
                        "name": "egress_gb",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Canonical transfer type (intra_region, inter_region, internet_egress)",
                        "name": "transfer_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Canonical region group (default: us-east)",
                        "name": "region",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Target currency code (default: USD)",
                        "name": "currency",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.NetworkComparisonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.RFC7807Error"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/middleware.RFC7807Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.RFC7807Error"
                        }
                    }
                }
            }
        },
        "/api/v1/prices/storage": {
            "get": {
                "description": "Returns normalized storage pricing across cloud providers (AWS, Azure, GCP) for requested specs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prices"
                ],
                "summary": "Get storage pricing comparison",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Requested storage size in GB (e.g. 500, max 1000000)",
                        "name": "size_gb",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Requested canonical storage class (e.g. standard, infrequent_access, archive)",
                        "name": "storage_class",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Canonical region group (default: us-east)",
                        "name": "region",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Target currency code (default: USD)",
                        "name": "currency",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.StorageComparisonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.RFC7807Error"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/middleware.RFC7807Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.RFC7807Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.ComputeAttributes": {
            "type": "object",
            "properties": {
                "family": {
                    "type": "string"
                },
                "ram_gb": {
                    "type": "number"
                },
                "vcpu": {
                    "type": "number"
                }
            }
        },
        "domain.NetworkAttributes": {
            "type": "object",
            "properties": {
                "egress_gb": {
                    "type": "number"
                },
                "transfer_type": {
                    "type": "string"
                }
            }
        },
        "domain.StorageAttributes": {
            "type": "object",
            "properties": {
                "iops": {
                    "description": "IOPS holds provisioned IOPS where reported (e.g. block storage EBS gp3/io2).\nCurrently unpopulated for S3/Blob/GCS object storage in stage 1.4.",
                    "type": "integer"
                },
                "size_gb": {
                    "type": "number"
                },
                "storage_class": {
                    "type": "string"
                }
            }
        },
        "middleware.RFC7807Error": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "instance": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "rest.CalculateComparisonMeta": {
            "type": "object",
            "properties": {
                "api_version": {
                    "type": "string"
                },
                "generated_at": {
                    "type": "string"
                }
            }
        },
        "rest.CalculateComparisonResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/rest.CalculateComparisonMeta"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.CalculateProviderResult"
                    }
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.ProviderWarning"
                    }
                }
            }
        },
        "rest.CalculateComputeRequest": {
            "type": "object",
            "properties": {
                "family": {
                    "type": "string"
                },
                "ram_gb": {
                    "type": "number"
                },
                "strict_family": {
                    "type": "boolean"
                },
                "vcpu": {
                    "type": "number"
                }
            }
        },
        "rest.CalculateNetworkRequest": {
            "type": "object",
            "properties": {
                "egress_gb": {
                    "type": "number"
                },
                "transfer_type": {
                    "type": "string"
                }
            }
        },
        "rest.CalculateRequestBody": {
            "type": "object",
            "properties": {
                "compute": {
                    "$ref": "#/definitions/rest.CalculateComputeRequest"
                },
                "currency": {
                    "type": "string"
                },
                "network": {
                    "$ref": "#/definitions/rest.CalculateNetworkRequest"
                },
                "region": {
                    "type": "string"
                },
                "storage": {
                    "$ref": "#/definitions/rest.CalculateStorageRequest"
                }
            }
        },
        "rest.CalculateStorageRequest": {
            "type": "object",
            "properties": {
                "size_gb": {
                    "type": "number"
                },
                "storage_class": {
                    "type": "string"
                }
            }
        },
        "rest.ComputeComparisonMeta": {
            "type": "object",
            "properties": {
                "api_version": {
                    "type": "string"
                },
                "generated_at": {
                    "type": "string"
                },
                "query": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "rest.ComputeComparisonResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/rest.ComputeComparisonMeta"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.ComputeResultEntry"
                    }
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.ProviderWarning"
                    }
                }
            }
        },
        "rest.ComputeResultEntry": {
            "type": "object",
            "properties": {
                "fetched_at": {
                    "type": "string"
                },
                "match_delta_pct": {
                    "type": "number"
                },
                "match_quality": {
                    "type": "string"
                },
                "matched_spec": {
                    "$ref": "#/definitions/domain.ComputeAttributes"
                },
                "missing_attributes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "normalized_hourly_usd": {
                    "type": "number"
                },
                "price": {
                    "$ref": "#/definitions/rest.PriceDetail"
                },
                "provider": {
                    "type": "string"
                },
                "sku_id": {
                    "type": "string"
                },
                "stale": {
                    "type": "boolean"
                }
            }
        },
        "rest.NetworkComparisonMeta": {
            "type": "object",
            "properties": {
                "api_version": {
                    "type": "string"
                },
                "generated_at": {
                    "type": "string"
                },
                "query": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "rest.NetworkComparisonResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/rest.NetworkComparisonMeta"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.NetworkResultEntry"
                    }
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.ProviderWarning"
                    }
                }
            }
        },
        "rest.NetworkResultEntry": {
            "type": "object",
            "properties": {
                "fetched_at": {
                    "type": "string"
                },
                "match_delta_pct": {
                    "type": "number"
                },
                "match_quality": {
                    "type": "string"
                },
                "matched_spec": {
                    "$ref": "#/definitions/domain.NetworkAttributes"
                },
                "missing_attributes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "monthly_cost_usd": {
                    "type": "number"
                },
                "price": {
                    "$ref": "#/definitions/rest.PriceDetail"
                },
                "provider": {
                    "type": "string"
                },
                "sku_id": {
                    "type": "string"
                },
                "stale": {
                    "type": "boolean"
                }
            }
        },
        "rest.PriceDetail": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "rest.ProviderWarning": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                }
            }
        },
        "rest.StorageComparisonMeta": {
            "type": "object",
            "properties": {
                "api_version": {
                    "type": "string"
                },
                "generated_at": {
                    "type": "string"
                },
                "query": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "rest.StorageComparisonResponse": {
            "type": "object",
            "properties": {
                "meta": {
                    "$ref": "#/definitions/rest.StorageComparisonMeta"
                },
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.StorageResultEntry"
                    }
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.ProviderWarning"
                    }
                }
            }
        },
        "rest.StorageResultEntry": {
            "type": "object",
            "properties": {
                "fetched_at": {
                    "type": "string"
                },
                "match_delta_pct": {
                    "type": "number"
                },
                "match_quality": {
                    "type": "string"
                },
                "matched_spec": {
                    "$ref": "#/definitions/domain.StorageAttributes"
                },
                "missing_attributes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "monthly_cost_usd": {
                    "type": "number"
                },
                "price": {
                    "$ref": "#/definitions/rest.PriceDetail"
                },
                "provider": {
                    "type": "string"
                },
                "sku_id": {
                    "type": "string"
                },
                "stale": {
                    "type": "boolean"
                }
            }
        },
        "service.CalculateCategoryResult": {
            "type": "object",
            "properties": {
                "match_quality": {
                    "type": "string"
                },
                "normalized_hourly_usd": {
                    "type": "number"
                },
                "sku_id": {
                    "type": "string"
                }
            }
        },
        "service.CalculateProviderResult": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/service.CalculateCategoryResult"
                    }
                },
                "partial": {
                    "type": "boolean"
                },
                "partial_total_normalized_hourly_usd": {
                    "type": "number"
                },
                "provider": {
                    "type": "string"
                },
                "total_normalized_hourly_usd": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
