// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: compute_catalog.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countComputeCatalogItems = `-- name: CountComputeCatalogItems :one
SELECT COUNT(*)::bigint
FROM compute_instance_catalog
WHERE ($1::text IS NULL OR provider = $1)
  AND ($2::text IS NULL OR category = $2)
  AND ($3::text IS NULL OR instance_family = $3)
  AND ($4::numeric IS NULL OR vcpu >= $4)
  AND ($5::numeric IS NULL OR vcpu <= $5)
  AND ($6::numeric IS NULL OR memory_gib >= $6)
  AND ($7::numeric IS NULL OR memory_gib <= $7)
`

type CountComputeCatalogItemsParams struct {
	Provider       pgtype.Text    `json:"provider"`
	Category       pgtype.Text    `json:"category"`
	InstanceFamily pgtype.Text    `json:"instance_family"`
	MinVcpu        pgtype.Numeric `json:"min_vcpu"`
	MaxVcpu        pgtype.Numeric `json:"max_vcpu"`
	MinMemoryGib   pgtype.Numeric `json:"min_memory_gib"`
	MaxMemoryGib   pgtype.Numeric `json:"max_memory_gib"`
}

func (q *Queries) CountComputeCatalogItems(ctx context.Context, arg CountComputeCatalogItemsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countComputeCatalogItems,
		arg.Provider,
		arg.Category,
		arg.InstanceFamily,
		arg.MinVcpu,
		arg.MaxVcpu,
		arg.MinMemoryGib,
		arg.MaxMemoryGib,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getComputeCatalogItem = `-- name: GetComputeCatalogItem :one
SELECT
    id,
    provider,
    instance_type_id,
    display_name,
    instance_family,
    category,
    vcpu,
    memory_gib,
    cpu_architecture,
    gpu_count,
    gpu_type,
    is_burstable,
    is_current_gen,
    first_seen_at,
    last_seen_at,
    attributes
FROM compute_instance_catalog
WHERE provider = $1 AND instance_type_id = $2
LIMIT 1
`

type GetComputeCatalogItemParams struct {
	Provider       string `json:"provider"`
	InstanceTypeID string `json:"instance_type_id"`
}

func (q *Queries) GetComputeCatalogItem(ctx context.Context, arg GetComputeCatalogItemParams) (ComputeInstanceCatalog, error) {
	row := q.db.QueryRow(ctx, getComputeCatalogItem, arg.Provider, arg.InstanceTypeID)
	var i ComputeInstanceCatalog
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.InstanceTypeID,
		&i.DisplayName,
		&i.InstanceFamily,
		&i.Category,
		&i.Vcpu,
		&i.MemoryGib,
		&i.CpuArchitecture,
		&i.GpuCount,
		&i.GpuType,
		&i.IsBurstable,
		&i.IsCurrentGen,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.Attributes,
	)
	return i, err
}

const getComputeCatalogSummary = `-- name: GetComputeCatalogSummary :many
SELECT
    provider,
    category,
    COUNT(*)::bigint AS instance_count
FROM compute_instance_catalog
GROUP BY provider, category
ORDER BY provider, category
`

type GetComputeCatalogSummaryRow struct {
	Provider      string `json:"provider"`
	Category      string `json:"category"`
	InstanceCount int64  `json:"instance_count"`
}

func (q *Queries) GetComputeCatalogSummary(ctx context.Context) ([]GetComputeCatalogSummaryRow, error) {
	rows, err := q.db.Query(ctx, getComputeCatalogSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetComputeCatalogSummaryRow
	for rows.Next() {
		var i GetComputeCatalogSummaryRow
		if err := rows.Scan(&i.Provider, &i.Category, &i.InstanceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalComputeInstanceCountByProvider = `-- name: GetTotalComputeInstanceCountByProvider :many
SELECT
    provider,
    COUNT(*)::bigint AS total_instances
FROM compute_instance_catalog
GROUP BY provider
ORDER BY total_instances DESC
`

type GetTotalComputeInstanceCountByProviderRow struct {
	Provider       string `json:"provider"`
	TotalInstances int64  `json:"total_instances"`
}

func (q *Queries) GetTotalComputeInstanceCountByProvider(ctx context.Context) ([]GetTotalComputeInstanceCountByProviderRow, error) {
	rows, err := q.db.Query(ctx, getTotalComputeInstanceCountByProvider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTotalComputeInstanceCountByProviderRow
	for rows.Next() {
		var i GetTotalComputeInstanceCountByProviderRow
		if err := rows.Scan(&i.Provider, &i.TotalInstances); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComputeCatalogItems = `-- name: ListComputeCatalogItems :many
SELECT
    id,
    provider,
    instance_type_id,
    display_name,
    instance_family,
    category,
    vcpu,
    memory_gib,
    cpu_architecture,
    gpu_count,
    gpu_type,
    is_burstable,
    is_current_gen,
    first_seen_at,
    last_seen_at,
    attributes
FROM compute_instance_catalog
WHERE ($3::text IS NULL OR provider = $3)
  AND ($4::text IS NULL OR category = $4)
  AND ($5::text IS NULL OR instance_family = $5)
  AND ($6::numeric IS NULL OR vcpu >= $6)
  AND ($7::numeric IS NULL OR vcpu <= $7)
  AND ($8::numeric IS NULL OR memory_gib >= $8)
  AND ($9::numeric IS NULL OR memory_gib <= $9)
ORDER BY provider, category, vcpu, memory_gib
LIMIT $1 OFFSET $2
`

type ListComputeCatalogItemsParams struct {
	Limit          int32          `json:"limit"`
	Offset         int32          `json:"offset"`
	Provider       pgtype.Text    `json:"provider"`
	Category       pgtype.Text    `json:"category"`
	InstanceFamily pgtype.Text    `json:"instance_family"`
	MinVcpu        pgtype.Numeric `json:"min_vcpu"`
	MaxVcpu        pgtype.Numeric `json:"max_vcpu"`
	MinMemoryGib   pgtype.Numeric `json:"min_memory_gib"`
	MaxMemoryGib   pgtype.Numeric `json:"max_memory_gib"`
}

func (q *Queries) ListComputeCatalogItems(ctx context.Context, arg ListComputeCatalogItemsParams) ([]ComputeInstanceCatalog, error) {
	rows, err := q.db.Query(ctx, listComputeCatalogItems,
		arg.Limit,
		arg.Offset,
		arg.Provider,
		arg.Category,
		arg.InstanceFamily,
		arg.MinVcpu,
		arg.MaxVcpu,
		arg.MinMemoryGib,
		arg.MaxMemoryGib,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComputeInstanceCatalog
	for rows.Next() {
		var i ComputeInstanceCatalog
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.InstanceTypeID,
			&i.DisplayName,
			&i.InstanceFamily,
			&i.Category,
			&i.Vcpu,
			&i.MemoryGib,
			&i.CpuArchitecture,
			&i.GpuCount,
			&i.GpuType,
			&i.IsBurstable,
			&i.IsCurrentGen,
			&i.FirstSeenAt,
			&i.LastSeenAt,
			&i.Attributes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertComputeCatalogItem = `-- name: UpsertComputeCatalogItem :one
INSERT INTO compute_instance_catalog (
    provider,
    instance_type_id,
    display_name,
    instance_family,
    category,
    vcpu,
    memory_gib,
    cpu_architecture,
    gpu_count,
    gpu_type,
    is_burstable,
    is_current_gen,
    first_seen_at,
    last_seen_at,
    attributes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (provider, instance_type_id)
DO UPDATE SET
    display_name = EXCLUDED.display_name,
    instance_family = EXCLUDED.instance_family,
    category = EXCLUDED.category,
    vcpu = EXCLUDED.vcpu,
    memory_gib = EXCLUDED.memory_gib,
    cpu_architecture = EXCLUDED.cpu_architecture,
    gpu_count = EXCLUDED.gpu_count,
    gpu_type = EXCLUDED.gpu_type,
    is_burstable = EXCLUDED.is_burstable,
    is_current_gen = EXCLUDED.is_current_gen,
    last_seen_at = EXCLUDED.last_seen_at,
    attributes = EXCLUDED.attributes
RETURNING id
`

type UpsertComputeCatalogItemParams struct {
	Provider        string             `json:"provider"`
	InstanceTypeID  string             `json:"instance_type_id"`
	DisplayName     string             `json:"display_name"`
	InstanceFamily  string             `json:"instance_family"`
	Category        string             `json:"category"`
	Vcpu            pgtype.Numeric     `json:"vcpu"`
	MemoryGib       pgtype.Numeric     `json:"memory_gib"`
	CpuArchitecture string             `json:"cpu_architecture"`
	GpuCount        int32              `json:"gpu_count"`
	GpuType         pgtype.Text        `json:"gpu_type"`
	IsBurstable     bool               `json:"is_burstable"`
	IsCurrentGen    bool               `json:"is_current_gen"`
	FirstSeenAt     pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	Attributes      []byte             `json:"attributes"`
}

func (q *Queries) UpsertComputeCatalogItem(ctx context.Context, arg UpsertComputeCatalogItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertComputeCatalogItem,
		arg.Provider,
		arg.InstanceTypeID,
		arg.DisplayName,
		arg.InstanceFamily,
		arg.Category,
		arg.Vcpu,
		arg.MemoryGib,
		arg.CpuArchitecture,
		arg.GpuCount,
		arg.GpuType,
		arg.IsBurstable,
		arg.IsCurrentGen,
		arg.FirstSeenAt,
		arg.LastSeenAt,
		arg.Attributes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
