// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fx_rates.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestFXRate = `-- name: GetLatestFXRate :one
SELECT id, base_currency, target_currency, rate, source, rate_date, fetched_at, created_at
FROM fx_rates
WHERE base_currency = $1 AND target_currency = $2
ORDER BY rate_date DESC, fetched_at DESC
LIMIT 1
`

type GetLatestFXRateParams struct {
	BaseCurrency   string `json:"base_currency"`
	TargetCurrency string `json:"target_currency"`
}

func (q *Queries) GetLatestFXRate(ctx context.Context, arg GetLatestFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, getLatestFXRate, arg.BaseCurrency, arg.TargetCurrency)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.TargetCurrency,
		&i.Rate,
		&i.Source,
		&i.RateDate,
		&i.FetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listLatestFXRates = `-- name: ListLatestFXRates :many
SELECT DISTINCT ON (base_currency, target_currency)
    id, base_currency, target_currency, rate, source, rate_date, fetched_at, created_at
FROM fx_rates
WHERE base_currency = $1
ORDER BY base_currency, target_currency, rate_date DESC, fetched_at DESC
`

func (q *Queries) ListLatestFXRates(ctx context.Context, baseCurrency string) ([]FxRate, error) {
	rows, err := q.db.Query(ctx, listLatestFXRates, baseCurrency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FxRate
	for rows.Next() {
		var i FxRate
		if err := rows.Scan(
			&i.ID,
			&i.BaseCurrency,
			&i.TargetCurrency,
			&i.Rate,
			&i.Source,
			&i.RateDate,
			&i.FetchedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFXRate = `-- name: UpsertFXRate :one
INSERT INTO fx_rates (
    base_currency,
    target_currency,
    rate,
    source,
    rate_date,
    fetched_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now()
)
ON CONFLICT (base_currency, target_currency, rate_date)
DO UPDATE SET
    rate = EXCLUDED.rate,
    source = EXCLUDED.source,
    fetched_at = EXCLUDED.fetched_at
RETURNING id, base_currency, target_currency, rate, source, rate_date, fetched_at, created_at
`

type UpsertFXRateParams struct {
	BaseCurrency   string             `json:"base_currency"`
	TargetCurrency string             `json:"target_currency"`
	Rate           pgtype.Numeric     `json:"rate"`
	Source         string             `json:"source"`
	RateDate       pgtype.Date        `json:"rate_date"`
	FetchedAt      pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) UpsertFXRate(ctx context.Context, arg UpsertFXRateParams) (FxRate, error) {
	row := q.db.QueryRow(ctx, upsertFXRate,
		arg.BaseCurrency,
		arg.TargetCurrency,
		arg.Rate,
		arg.Source,
		arg.RateDate,
		arg.FetchedAt,
	)
	var i FxRate
	err := row.Scan(
		&i.ID,
		&i.BaseCurrency,
		&i.TargetCurrency,
		&i.Rate,
		&i.Source,
		&i.RateDate,
		&i.FetchedAt,
		&i.CreatedAt,
	)
	return i, err
}
