// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ComputeInstanceCatalog struct {
	ID              int64              `json:"id"`
	Provider        string             `json:"provider"`
	InstanceTypeID  string             `json:"instance_type_id"`
	DisplayName     string             `json:"display_name"`
	InstanceFamily  string             `json:"instance_family"`
	Category        string             `json:"category"`
	Vcpu            pgtype.Numeric     `json:"vcpu"`
	MemoryGib       pgtype.Numeric     `json:"memory_gib"`
	CpuArchitecture string             `json:"cpu_architecture"`
	GpuCount        int32              `json:"gpu_count"`
	GpuType         pgtype.Text        `json:"gpu_type"`
	IsBurstable     bool               `json:"is_burstable"`
	IsCurrentGen    bool               `json:"is_current_gen"`
	FirstSeenAt     pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	Attributes      []byte             `json:"attributes"`
}

type FxRate struct {
	ID             int64              `json:"id"`
	BaseCurrency   string             `json:"base_currency"`
	TargetCurrency string             `json:"target_currency"`
	Rate           pgtype.Numeric     `json:"rate"`
	Source         string             `json:"source"`
	RateDate       pgtype.Date        `json:"rate_date"`
	FetchedAt      pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PriceObservation struct {
	ID              int64              `json:"id"`
	Provider        string             `json:"provider"`
	ServiceCategory string             `json:"service_category"`
	SkuID           string             `json:"sku_id"`
	DisplayName     string             `json:"display_name"`
	Region          string             `json:"region"`
	RegionGroup     string             `json:"region_group"`
	Unit            string             `json:"unit"`
	PriceAmount     pgtype.Numeric     `json:"price_amount"`
	PriceCurrency   string             `json:"price_currency"`
	PricingModel    string             `json:"pricing_model"`
	Attributes      []byte             `json:"attributes"`
	RawResponseRef  pgtype.Text        `json:"raw_response_ref"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	AnomalyStatus   pgtype.Text        `json:"anomaly_status"`
}

type RefreshToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	FamilyID   pgtype.UUID        `json:"family_id"`
	TokenHash  string             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
