// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PriceObservation struct {
	ID              int64              `json:"id"`
	Provider        string             `json:"provider"`
	ServiceCategory string             `json:"service_category"`
	SkuID           string             `json:"sku_id"`
	DisplayName     string             `json:"display_name"`
	Region          string             `json:"region"`
	RegionGroup     string             `json:"region_group"`
	Unit            string             `json:"unit"`
	PriceAmount     pgtype.Numeric     `json:"price_amount"`
	PriceCurrency   string             `json:"price_currency"`
	PricingModel    string             `json:"pricing_model"`
	Attributes      []byte             `json:"attributes"`
	RawResponseRef  pgtype.Text        `json:"raw_response_ref"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	AnomalyStatus   pgtype.Text        `json:"anomaly_status"`
}
