// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: price_observations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestPriceForSKU = `-- name: GetLatestPriceForSKU :one
SELECT
    id,
    provider,
    service_category,
    sku_id,
    display_name,
    region,
    region_group,
    unit,
    price_amount,
    price_currency,
    pricing_model,
    attributes,
    raw_response_ref,
    fetched_at,
    last_seen_at,
    anomaly_status
FROM price_observations
WHERE provider = $1
  AND sku_id = $2
  AND region = $3
ORDER BY fetched_at DESC
LIMIT 1
`

type GetLatestPriceForSKUParams struct {
	Provider string `json:"provider"`
	SkuID    string `json:"sku_id"`
	Region   string `json:"region"`
}

func (q *Queries) GetLatestPriceForSKU(ctx context.Context, arg GetLatestPriceForSKUParams) (PriceObservation, error) {
	row := q.db.QueryRow(ctx, getLatestPriceForSKU, arg.Provider, arg.SkuID, arg.Region)
	var i PriceObservation
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ServiceCategory,
		&i.SkuID,
		&i.DisplayName,
		&i.Region,
		&i.RegionGroup,
		&i.Unit,
		&i.PriceAmount,
		&i.PriceCurrency,
		&i.PricingModel,
		&i.Attributes,
		&i.RawResponseRef,
		&i.FetchedAt,
		&i.LastSeenAt,
		&i.AnomalyStatus,
	)
	return i, err
}

const getPriceObservations = `-- name: GetPriceObservations :many
SELECT
    id,
    provider,
    service_category,
    sku_id,
    display_name,
    region,
    region_group,
    unit,
    price_amount,
    price_currency,
    pricing_model,
    attributes,
    raw_response_ref,
    fetched_at,
    last_seen_at,
    anomaly_status
FROM price_observations
WHERE provider = $1
  AND service_category = $2
  AND region_group = $3
ORDER BY fetched_at DESC
`

type GetPriceObservationsParams struct {
	Provider        string `json:"provider"`
	ServiceCategory string `json:"service_category"`
	RegionGroup     string `json:"region_group"`
}

func (q *Queries) GetPriceObservations(ctx context.Context, arg GetPriceObservationsParams) ([]PriceObservation, error) {
	rows, err := q.db.Query(ctx, getPriceObservations, arg.Provider, arg.ServiceCategory, arg.RegionGroup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PriceObservation
	for rows.Next() {
		var i PriceObservation
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ServiceCategory,
			&i.SkuID,
			&i.DisplayName,
			&i.Region,
			&i.RegionGroup,
			&i.Unit,
			&i.PriceAmount,
			&i.PriceCurrency,
			&i.PricingModel,
			&i.Attributes,
			&i.RawResponseRef,
			&i.FetchedAt,
			&i.LastSeenAt,
			&i.AnomalyStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPriceObservation = `-- name: InsertPriceObservation :one
INSERT INTO price_observations (
    provider,
    service_category,
    sku_id,
    display_name,
    region,
    region_group,
    unit,
    price_amount,
    price_currency,
    pricing_model,
    attributes,
    raw_response_ref,
    fetched_at,
    last_seen_at,
    anomaly_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id
`

type InsertPriceObservationParams struct {
	Provider        string             `json:"provider"`
	ServiceCategory string             `json:"service_category"`
	SkuID           string             `json:"sku_id"`
	DisplayName     string             `json:"display_name"`
	Region          string             `json:"region"`
	RegionGroup     string             `json:"region_group"`
	Unit            string             `json:"unit"`
	PriceAmount     pgtype.Numeric     `json:"price_amount"`
	PriceCurrency   string             `json:"price_currency"`
	PricingModel    string             `json:"pricing_model"`
	Attributes      []byte             `json:"attributes"`
	RawResponseRef  pgtype.Text        `json:"raw_response_ref"`
	FetchedAt       pgtype.Timestamptz `json:"fetched_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	AnomalyStatus   pgtype.Text        `json:"anomaly_status"`
}

func (q *Queries) InsertPriceObservation(ctx context.Context, arg InsertPriceObservationParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPriceObservation,
		arg.Provider,
		arg.ServiceCategory,
		arg.SkuID,
		arg.DisplayName,
		arg.Region,
		arg.RegionGroup,
		arg.Unit,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.PricingModel,
		arg.Attributes,
		arg.RawResponseRef,
		arg.FetchedAt,
		arg.LastSeenAt,
		arg.AnomalyStatus,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
