// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_status.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProviderCategoryStatus = `-- name: GetProviderCategoryStatus :many
SELECT
    service_category,
    MAX(fetched_at)::timestamptz AS last_fetched_at,
    MAX(last_seen_at)::timestamptz AS last_seen_at,
    COUNT(*)::bigint AS observation_count
FROM price_observations
WHERE provider = $1
GROUP BY service_category
`

type GetProviderCategoryStatusRow struct {
	ServiceCategory  string             `json:"service_category"`
	LastFetchedAt    pgtype.Timestamptz `json:"last_fetched_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	ObservationCount int64              `json:"observation_count"`
}

func (q *Queries) GetProviderCategoryStatus(ctx context.Context, provider string) ([]GetProviderCategoryStatusRow, error) {
	rows, err := q.db.Query(ctx, getProviderCategoryStatus, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProviderCategoryStatusRow
	for rows.Next() {
		var i GetProviderCategoryStatusRow
		if err := rows.Scan(
			&i.ServiceCategory,
			&i.LastFetchedAt,
			&i.LastSeenAt,
			&i.ObservationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
