// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (
    user_id,
    family_id,
    token_hash,
    expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, family_id, token_hash, created_at, expires_at, revoked_at, replaced_by
`

type InsertRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	FamilyID  pgtype.UUID        `json:"family_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}
