// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_tokens.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeVerificationToken = `-- name: ConsumeVerificationToken :exec
UPDATE verification_tokens
SET consumed_at = $1
WHERE id = $2 AND consumed_at IS NULL
`

type ConsumeVerificationTokenParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	ID         pgtype.UUID        `json:"id"`
}

func (q *Queries) ConsumeVerificationToken(ctx context.Context, arg ConsumeVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, consumeVerificationToken, arg.ConsumedAt, arg.ID)
	return err
}

const countActiveTokensByUser = `-- name: CountActiveTokensByUser :one
SELECT COUNT(*) FROM verification_tokens
WHERE user_id = $1
  AND purpose = $2
  AND consumed_at IS NULL
  AND expires_at > $3
`

type CountActiveTokensByUserParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Purpose   string             `json:"purpose"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CountActiveTokensByUser(ctx context.Context, arg CountActiveTokensByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTokensByUser, arg.UserID, arg.Purpose, arg.ExpiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVerificationTokenByHash = `-- name: GetVerificationTokenByHash :one
SELECT id, user_id, token_hash, purpose, created_at, expires_at, consumed_at
FROM verification_tokens
WHERE token_hash = $1
`

func (q *Queries) GetVerificationTokenByHash(ctx context.Context, tokenHash string) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationTokenByHash, tokenHash)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const insertVerificationToken = `-- name: InsertVerificationToken :one
INSERT INTO verification_tokens (user_id, token_hash, purpose, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, purpose, created_at, expires_at, consumed_at
`

type InsertVerificationTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	Purpose   string             `json:"purpose"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertVerificationToken(ctx context.Context, arg InsertVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, insertVerificationToken,
		arg.UserID,
		arg.TokenHash,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Purpose,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const revokeUnconsumedTokensByUser = `-- name: RevokeUnconsumedTokensByUser :exec
UPDATE verification_tokens
SET consumed_at = $1
WHERE user_id = $2
  AND purpose = $3
  AND consumed_at IS NULL
`

type RevokeUnconsumedTokensByUserParams struct {
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	UserID     pgtype.UUID        `json:"user_id"`
	Purpose    string             `json:"purpose"`
}

func (q *Queries) RevokeUnconsumedTokensByUser(ctx context.Context, arg RevokeUnconsumedTokensByUserParams) error {
	_, err := q.db.Exec(ctx, revokeUnconsumedTokensByUser, arg.ConsumedAt, arg.UserID, arg.Purpose)
	return err
}
